// Minimal LiveKit Go SDK publisher used by OpenViduTestAppE2eServerSdkTest
// See ../README.md
package main

import (
	"fmt"
	"io"
	"log"
	"os"
	"strings"
	"time"

	"github.com/pion/webrtc/v4"
	"github.com/pion/webrtc/v4/pkg/media"
	"github.com/pion/webrtc/v4/pkg/media/h264reader"
	"github.com/pion/webrtc/v4/pkg/media/ivfreader"

	"github.com/livekit/protocol/livekit"
	lksdk "github.com/livekit/server-sdk-go/v2"
)

const frameDuration = time.Second / 30

var mimeTypes = map[string]string{
	"vp8":  webrtc.MimeTypeVP8,
	"h264": webrtc.MimeTypeH264,
	"vp9":  webrtc.MimeTypeVP9,
	"av1":  webrtc.MimeTypeAV1,
}

type simulcastLayer struct {
	quality       livekit.VideoQuality
	width, height uint32
	fileEnv       string
}

// Simulcast layers per VIDEO_LAYERS value, lowest first (the sizes must match
// the files generated by OpenViduTestE2e#startServerSdkPublisher). The last
// layer is the source size declared in the publication.
var simulcastLayers = map[string][]simulcastLayer{
	"2": {
		{livekit.VideoQuality_LOW, 320, 240, "VIDEO_FILE_LOW"},
		{livekit.VideoQuality_HIGH, 640, 480, "VIDEO_FILE_HIGH"},
	},
	"3": {
		{livekit.VideoQuality_LOW, 320, 180, "VIDEO_FILE_LOW"},
		{livekit.VideoQuality_MEDIUM, 640, 360, "VIDEO_FILE_MEDIUM"},
		{livekit.VideoQuality_HIGH, 1280, 720, "VIDEO_FILE_HIGH"},
	},
}

func main() {
	mimeType, ok := mimeTypes[os.Getenv("VIDEO_CODEC")]
	if !ok {
		log.Fatalf("unknown VIDEO_CODEC %q", os.Getenv("VIDEO_CODEC"))
	}
	codec := webrtc.RTPCodecCapability{MimeType: mimeType, ClockRate: 90000}

	room, err := lksdk.ConnectToRoomWithToken(os.Getenv("LIVEKIT_URL"), os.Getenv("LIVEKIT_TOKEN"), &lksdk.RoomCallback{})
	if err != nil {
		log.Fatalf("could not connect to room: %v", err)
	}
	defer room.Disconnect()

	layers := os.Getenv("VIDEO_LAYERS")
	if layers == "" {
		layers = "1"
	}
	if layers != "1" {
		layerDefs, ok := simulcastLayers[layers]
		if !ok {
			log.Fatalf("unsupported VIDEO_LAYERS %q", layers)
		}
		tracks := make([]*lksdk.LocalTrack, 0, len(layerDefs))
		for _, layer := range layerDefs {
			track, err := lksdk.NewLocalSampleTrack(codec, lksdk.WithSimulcast("go-video",
				&livekit.VideoLayer{Quality: layer.quality, Width: layer.width, Height: layer.height}))
			if err != nil {
				log.Fatalf("could not create local track: %v", err)
			}
			tracks = append(tracks, track)
		}
		top := layerDefs[len(layerDefs)-1]
		if _, err = room.LocalParticipant.PublishSimulcastTrack(tracks, &lksdk.TrackPublicationOptions{
			Name:        "go-video",
			VideoWidth:  int(top.width),
			VideoHeight: int(top.height),
		}); err != nil {
			log.Fatalf("could not publish simulcast track: %v", err)
		}
		// The Java test waits for this exact log line before asserting.
		fmt.Println("TRACK_PUBLISHED")
		for i, layer := range layerDefs {
			go loopVideoFile(tracks[i], os.Getenv(layer.fileEnv))
		}
		select {}
	}

	track, err := lksdk.NewLocalSampleTrack(codec)
	if err != nil {
		log.Fatalf("could not create local track: %v", err)
	}
	if _, err = room.LocalParticipant.PublishTrack(track, &lksdk.TrackPublicationOptions{
		Name:        "go-video",
		VideoWidth:  640,
		VideoHeight: 480,
	}); err != nil {
		log.Fatalf("could not publish track: %v", err)
	}
	// The Java test waits for this exact log line before asserting.
	fmt.Println("TRACK_PUBLISHED")
	loopVideoFile(track, os.Getenv("VIDEO_FILE"))
}

// loopVideoFile sends the frames of the file forever, paced at 30 fps.
func loopVideoFile(track *lksdk.LocalTrack, path string) {
	for {
		if err := writeVideoFileOnce(track, path); err != nil {
			log.Fatalf("could not write video samples of %s: %v", path, err)
		}
	}
}

// writeVideoFileOnce sends every frame of the file once, paced at 30 fps.
func writeVideoFileOnce(track *lksdk.LocalTrack, path string) error {
	file, err := os.Open(path)
	if err != nil {
		return err
	}
	defer file.Close()

	var nextFrame func() ([]byte, error)
	if strings.HasSuffix(file.Name(), ".h264") {
		reader, err := h264reader.NewReader(file)
		if err != nil {
			return err
		}
		nextFrame = func() ([]byte, error) {
			nal, err := reader.NextNAL()
			if err != nil {
				return nil, err
			}
			return nal.Data, nil
		}
	} else {
		reader, _, err := ivfreader.NewWith(file)
		if err != nil {
			return err
		}
		nextFrame = func() ([]byte, error) {
			frame, _, err := reader.ParseNextFrame()
			return frame, err
		}
	}

	ticker := time.NewTicker(frameDuration)
	defer ticker.Stop()
	for {
		data, err := nextFrame()
		if err == io.EOF {
			return nil
		}
		if err != nil {
			return err
		}
		if err := track.WriteSample(media.Sample{Data: data, Duration: frameDuration}, nil); err != nil {
			return err
		}
		<-ticker.C
	}
}
